# Generated by Django 4.2.8 on 2024-02-03 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_products_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Product_SubCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productsubcategories', to='mainapp.productsubcategory'),
        ),
    ]
