# Generated by Django 4.2.8 on 2024-02-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_productimage_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='sizes',
            new_name='size',
        ),
    ]
