# Generated by Django 4.2.8 on 2024-02-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_productimage_color_remove_productimage_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='order',
        ),
        migrations.AddField(
            model_name='productimage',
            name='color_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
