# Generated by Django 4.2.8 on 2024-02-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_productimage_order_productimage_color_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='order',
        ),
    ]
