# Generated by Django 4.2.8 on 2024-05-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_productsize_remove_productimage_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product_size',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_size',
            field=models.ManyToManyField(to='mainapp.productsize'),
        ),
    ]
