# Generated by Django 4.2.8 on 2024-05-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_color_product_size_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
    ]
