# Generated by Django 4.2.8 on 2024-05-04 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_remove_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='color',
        ),
        migrations.AddField(
            model_name='productimage',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.color'),
        ),
    ]
