# Generated by Django 4.2.8 on 2024-05-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
