# Generated by Django 4.2.8 on 2024-05-07 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0023_alter_order_user_alter_product_product_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistproduct',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
