# Generated by Django 4.2.8 on 2024-05-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_questionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.product'),
        ),
    ]
