# Generated by Django 4.2.8 on 2024-05-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_deliveryfee_status_shippingadress_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryfee',
            name='duration',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
