# Generated by Django 4.2.8 on 2024-05-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_remove_product_brandname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
