# Generated by Django 4.2.8 on 2024-05-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_brand_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
    ]
