# Generated by Django 3.2 on 2024-10-29 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_remove_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingadress',
            name='district',
        ),
        migrations.RemoveField(
            model_name='shippingadress',
            name='division',
        ),
        migrations.RemoveField(
            model_name='shippingadress',
            name='upazila',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.IntegerField(default=0)),
                ('sold_quantity', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('variation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='mainapp.variant')),
            ],
        ),
    ]
