# Generated by Django 3.2 on 2024-10-29 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_auto_20241029_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.material'),
        ),
    ]
