# Generated by Django 3.2 on 2024-10-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_alter_product_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='material',
            new_name='materials',
        ),
    ]
