# Generated by Django 3.2 on 2024-10-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_rename_material_product_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='materials',
        ),
    ]
