# Generated by Django 3.2 on 2024-11-17 13:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_auto_20241117_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icons',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icons'),
        ),
        migrations.AlterField(
            model_name='displaymarketing',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_images'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='subcategory'),
        ),
    ]
