# Generated by Django 3.2 on 2024-11-17 13:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_auto_20241117_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaymarketing',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='display'),
        ),
    ]
